language: python
python:
  - "3.8"
env:
    - SECRET_KEY='TEST'
install:
  - pip install -r requirements.txt
# command to run tests
services:
virtualenv:
  system_site_packages: true
script:
  - python manage.py test