# Generated by Django 3.1.2 on 2020-12-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
