# Generated by Django 3.1.2 on 2020-12-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_entity_entity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=120)),
                ('field_info', models.JSONField()),
            ],
        ),
    ]
